{"DeploymentId":"EFFBAE0C1E2640D28395DF30F32284E4","ErrorCode":0,"ErrorCodeMsg":"","EventId":"4","Function":"","Level":4,"Message":{"ClientId":null,"DeviceId":null,"ErrorCode":0,"ErrorCodeMsg":"","Message":"Request Begin: E21A04D188CA4C93BCF70151259138AB\r\n","Payload":{"HttpMethod":"GET","RequestUri":"http://localhost:19677/Log/Exception","Authorization":null,"Referrer":"http://localhost:19677/swagger/ui/index","UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36","X-JYM-RID":"E21A04D188CA4C93BCF70151259138AB","Content":""},"RequestId":null,"SessionId":null,"Tag":"ASP.NET HTTP Request","UserId":null},"PreciseTimestamp":"2015-11-20T07:44:12.972138Z","Role":"MoeLibWebLab","RoleInstance":"MoeLibWebLab_10.1.4.5"}
{"DeploymentId":"EFFBAE0C1E2640D28395DF30F32284E4","ErrorCode":0,"ErrorCodeMsg":"","EventId":"2","Function":"","Level":2,"Message":{"ClientId":null,"DeviceId":null,"ErrorCode":0,"ErrorCodeMsg":"","Message":"This is for testing exception logger\r\n\r\nException(s) Found:\r\nType: System.ApplicationException\r\nMessage: This is for testing exception logger\r\nSource: MoeLibWebLab\r\nStacktrace:\r\n   at MoeLibWebLab.Controllers.LogController.GetException() in C:\\Users\\lu.siqi\\Repositories\\Moe\\Repositories\\MoeLib\\MoeLibWebLab\\Controllers\\LogController.cs:line 16\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<ExecuteAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n\r\n  Inner \r\nException(s) Found:\r\n  Type: System.ApplicationException\r\n  Message: This is the first inner exception.\r\n  Source: \r\n  Stacktrace:\r\n\r\n\r\n    Inner \r\nException(s) Found:\r\n    Type: System.ApplicationException\r\n    Message: This is the second inner exception.\r\n    Source: \r\n    Stacktrace:\r\n\r\n\r\n","Payload":{"HttpMethod":"GET","RequestUri":"http://localhost:19677/Log/Exception","Authorization":null,"Referrer":"http://localhost:19677/swagger/ui/index","UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36","X-JYM-RID":"E21A04D188CA4C93BCF70151259138AB","Content":""},"RequestId":null,"SessionId":null,"Tag":"ASP.NET Error","UserId":null},"PreciseTimestamp":"2015-11-20T07:44:22.6831755Z","Role":"MoeLibWebLab","RoleInstance":"MoeLibWebLab_10.1.4.5"}
{"DeploymentId":"EFFBAE0C1E2640D28395DF30F32284E4","ErrorCode":0,"ErrorCodeMsg":"","EventId":"4","Function":"","Level":4,"Message":{"ClientId":null,"DeviceId":null,"ErrorCode":0,"ErrorCodeMsg":"","Message":"Request End: E21A04D188CA4C93BCF70151259138AB\r\n","Payload":{"ResponseStatusCode":500,"ResponseContent":"{\"Message\":\"An error has occurred.\",\"ExceptionMessage\":\"This is for testing exception logger\",\"ExceptionType\":\"System.ApplicationException\",\"StackTrace\":\"   at MoeLibWebLab.Controllers.LogController.GetException() in C:\\\\Users\\\\lu.siqi\\\\Repositories\\\\Moe\\\\Repositories\\\\MoeLib\\\\MoeLibWebLab\\\\Controllers\\\\LogController.cs:line 16\\r\\n   at lambda_method(Closure , Object , Object[] )\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<ExecuteAsyncCore>d__5.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\",\"InnerException\":{\"Message\":\"An error has occurred.\",\"ExceptionMessage\":\"This is the first inner exception.\",\"ExceptionType\":\"System.ApplicationException\",\"StackTrace\":null,\"InnerException\":{\"Message\":\"An error has occurred.\",\"ExceptionMessage\":\"This is the second inner exception.\",\"ExceptionType\":\"System.ApplicationException\",\"StackTrace\":null}}}","HttpMethod":"GET","RequestUri":"http://localhost:19677/Log/Exception","Authorization":null,"Referrer":"http://localhost:19677/swagger/ui/index","UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36","X-JYM-RID":"E21A04D188CA4C93BCF70151259138AB","Content":""},"RequestId":null,"SessionId":null,"Tag":"ASP.NET HTTP Response","UserId":null},"PreciseTimestamp":"2015-11-20T07:44:39.3389646Z","Role":"MoeLibWebLab","RoleInstance":"MoeLibWebLab_10.1.4.5"}
